TARGET=Mega2560
SSH_UPLOAD_HOST=nano1
GITHUB_REPOS=adafruit/Adafruit_BNO055 \
adafruit/Adafruit-GFX-Library \
adafruit/Adafruit_Neopixel \
adafruit/Adafruit_Sensor \
adafruit/Adafruit-SSD1331-OLED-Driver-Library-for-Arduino \
reeltwo/Reeltwo

include ../Arduino.mk
