TARGET=Mega2560
SSH_UPLOAD_HOST=r2p2
#SSH_UPLOAD_HOST=192.168.8.209
GITHUB_REPOS=adafruit/Adafruit_BNO055 \
adafruit/Adafruit-GFX-Library \
adafruit/Adafruit_Neopixel \
adafruit/Adafruit_Sensor \
adafruit/Adafruit-SSD1331-OLED-Driver-Library-for-Arduino \
reeltwo/Reeltwo

ARDUINO_OPTS+='-prefs="compiler.cpp.extra_flags=-DRLD_UPSIDE_DOWN=1"'

include ../Arduino.mk
