PORT=/dev/ttyUSB4
TARGET=Mega2560
UPLOAD_HOSTS=r2b2
GITHUB_REPOS=adafruit/Adafruit_BNO055 \
adafruit/Adafruit_Neopixel \
adafruit/Adafruit_Sensor \
reeltwo/Reeltwo \
rimim/USBSabertooth_NB
include ../Arduino.mk
